name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # ───────────────────────────────────────────────────────
  # 1. Кэшируем LFS-данные (producer)
  # ───────────────────────────────────────────────────────
  cache_lfs:
    runs-on: ubuntu-latest
    outputs:
      lfs_sha: ${{ steps.lfs_sha_recover.outputs.lfs_sha }}
    steps:
      - name: Checkout repository (no LFS)
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 1
          path: source

      - name: Cache LFS Data
        id: lfs_sha_recover
        uses: f3d-app/lfs-data-cache-action@v1
        with:
          type: producer
          repository: ${{ github.repository }}
          target_directory: source

  # ───────────────────────────────────────────────────────
  # 2. Основная сборка и деплой (consumer)
  # ───────────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    needs: cache_lfs
    steps:
      - name: Checkout repository (no LFS)
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0
          path: source

      - name: Recover LFS Data
        uses: f3d-app/lfs-data-cache-action@v1
        with:
          type: consumer
          repository: ${{ github.repository }}
          lfs_sha: ${{ needs.cache_lfs.outputs.lfs_sha }}
          target_directory: source

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: source
        run: pnpm install

      - name: Build site
        working-directory: source
        run: pnpm exec eleventy

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: source/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
